## Clock signal (Nexys A7 100MHz)
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## USB-RS232 Interface (Nexys A7)
set_property PACKAGE_PIN C4 [get_ports uart_rx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_pin]

set_property PACKAGE_PIN D4 [get_ports uart_tx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_pin]

## Buttons (Nexys A7 Center Button - BTNC)
set_property PACKAGE_PIN N17 [get_ports rst_btn]
set_property IOSTANDARD LVCMOS33 [get_ports rst_btn]

## LEDs (Nexys A7 LED0 to LED15)
set_property PACKAGE_PIN H17 [get_ports {match_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[0]}]
set_property PACKAGE_PIN K15 [get_ports {match_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[1]}]
set_property PACKAGE_PIN J13 [get_ports {match_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[2]}]
set_property PACKAGE_PIN N14 [get_ports {match_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[3]}]
set_property PACKAGE_PIN R18 [get_ports {match_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[4]}]
set_property PACKAGE_PIN V17 [get_ports {match_leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[5]}]
set_property PACKAGE_PIN U17 [get_ports {match_leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[6]}]
set_property PACKAGE_PIN U16 [get_ports {match_leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[7]}]
set_property PACKAGE_PIN V16 [get_ports {match_leds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[8]}]
set_property PACKAGE_PIN T15 [get_ports {match_leds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[9]}]
set_property PACKAGE_PIN U14 [get_ports {match_leds[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[10]}]
set_property PACKAGE_PIN T16 [get_ports {match_leds[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[11]}]
set_property PACKAGE_PIN V15 [get_ports {match_leds[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[12]}]
set_property PACKAGE_PIN V14 [get_ports {match_leds[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[13]}]
set_property PACKAGE_PIN V12 [get_ports {match_leds[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[14]}]
set_property PACKAGE_PIN V11 [get_ports {match_leds[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_leds[15]}]
